### ISSUE TITLE
sp module breaking

### ISSUE THREAD

**Issue by VedranIteh** [Dukecitysolutions/Sentora-Live-v1.0.3.1#14]
PHP Fatal error: [snuffleupagus][0.0.0.0][disabled_function] Aborted execution on call of the function 'exec', because its argument '$command' content (cd /var/sentora/hostdata/example/ && zip -r9 /etc/sentora/panel/etc/tmp/example_Jan-14-2020_080113 public_html/*) matched a rule in /etc/sentora/panel/modules/backupmgr/code/dobackup.php on line 105, referer: https://example/modules/backupmgr/code/launchbackup.php?id=30

There's another bug in this module too that I didn't care to investigate more so for now it is actually a positive thing. exec function is in a lot of other modules also.

**Comment by Dukecitysolutions** [comment]
Exec is needed to run some commands in Sentora. I will allow it in snuff Sentora.rules tell we can secure/isolate the panel. Hopefully, we can change sentora PHP exec functions to scripts to isolate/protect commands down the road with cron/zdaemon. Will fix/release in next Build soon. Thank you for finding this.

**Comment by Dukecitysolutions** [comment]
Fixed with new release v1.0.3.1-build 0.3.4-BETA run command below to update.

`bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/update.sh)`

UPDATE: Repos will be ONLINE tomorrow too tired to continue. Stand by.
